version: "3"

services:
  server:
    build: .
    env_file: .env.prod
    restart: always
    volumes:
      - ./logs/app:/usr/src/app/logs
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:5.6.51
    container_name: mysql-db
    env_file: .env.prod
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql/
      - ./mysql:/etc/mysql/mysql.conf.d/
    ports:
      - 3306:3306
    restart: always

  redis:
    image: redis
    env_file: .env.prod
    container_name: cache
    expose:
      - 6379
  
  nginx:
    image: nginx:1.19.3
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/copy/quotes.bhanunadar.com:/etc/ssl/
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
