version: "3"

services:
  server:
    build: .
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    env_file: .env.dev
    restart: always
    depends_on:
      - redis
    ports:
      - 80:3000
      - 443:3000

  mysql:
    image: mysql:5.6.51
    container_name: mysql-db
    env_file: .env.dev
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: redis
    env_file: .env.dev
    container_name: cache
    expose:
      - 6379
